# notification.yml
name: Shared Workflow - Notification

jobs:
  ending-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ inputs.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE="Your workflow has completed successfully!"
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "'"${MESSAGE}"'"
          }' "${TEAMS_WEBHOOK_URL}"
