# notification.yml
name: Shared Workflow - Notification

on:
  workflow_call:
    inputs:
      message:
        description: 'The message to send'
        required: true
        type: string
    secrets:
      TEAMS_WEBHOOK_URL:
        description: 'TEAMS_WEBHOOK_URL'
        required: true

jobs:
  ending-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Send Notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE="${{ inputs.message }}"
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "'"${MESSAGE}"'"
          }' "${TEAMS_WEBHOOK_URL}"
