name: Shared Workflow 
on:
  workflow_run:
    workflows: ["Maven-poc"]  # Replace with the name of your main workflow
    types:
      - completed

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE="Your workflow has completed successfully!"
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "'"${MESSAGE}"'"
          }' "${TEAMS_WEBHOOK_URL}"

      
